### ISSUE TITLE
Create FAB button that creates/searches offer

### ISSUE THREAD

**Issue by unrevised6419** [code4moldova/shelterapp#4]
- positioned bottom right
- opens dialog to chose offer/search
- offer/search should open other forms (TBD)

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1881266/155857555-47cba252-5b08-4366-af6c-229bba5f3325.png">

<img width="411" alt="image" src="https://user-images.githubusercontent.com/1881266/155857604-3fd83e08-f17d-46d4-88f6-8994c0744cde.png">

https://help.kartiero.md/mindex.html

**Comment by Raduc4** [comment]
assigned
// just add button component and modal window with 2 options for moment

**Comment by unrevised6419** [comment]
I'm working on form inside second dialog
